### ISSUE TITLE
subscribing to blog posts by email

### ISSUE THREAD

**Issue by sfilinto** [LucianFrango/public-AMA#1]
nice blog !! is there a way to subscribe to new posts via email ?
( btw... also a nice replacement to the traditional comments section )

Best Regards,
Sachin Filinto.

**Comment by LucianFrango** [comment]
Thanks mate, i'm working on an RSS. My preference is to use that over a subscription service and capture email aliases. I'd like to respect everyones privacy. I should have that sorted within the next week.

**Comment by LucianFrango** [comment]
Hey Sachin, ive added an RSS: https://lucian.blog/rss.xml. Enjoy!
