### ISSUE TITLE
Azure Firewall Management

### ISSUE THREAD

**Issue by muss11** [LucianFrango/public-AMA#2]
Hi Lucian, 

I came across your work about working with NSG rules and I wondered whether you have scripted anything to do with Azure Firewall management.

I'm currently working on a task where I need to create a Powershell script to export firewall network / application rule collections with their corresponding rules to a CSV and import them back again. I'm still new to PS so I've been scouring the Internet to see if anyone has done something similar but no luck so far.

Any help would be appreciated.

Many Thanks

Mustafa

**Comment by LucianFrango** [comment]
Hi mate, sorry I missed seeing this earlier. 

Recently I've ben using Terraform to manage Azure Firewall rules. 
See https://lucian.blog/blocking-hackers-with-azure-firewall-efficiently/ for some detail on that.

Not used PS to manage AzFW where I've got scripts in any public repo as yet.
Perhaps something may come up.
If anything does, i'll put that in my azure-public repo.
